### ISSUE TITLE
Service client classes should not be marked as final.

### ISSUE THREAD

**Issue by 77web** [googleads/google-ads-php#1008]
[DO NOT INCLUDE ANY PERSONAL OR SENSITIVE DATA - MAKE SURE TO REDACT CONTENT WHEN NECESSARY]

**Your client library and Google Ads API versions:**

* Client library version: `v22.1.0`

* Google Ads API version: `V16`

**Your environment:**

**Description of the bug:**

Service Clients are marked as final.

**Steps to reproduce:**

see https://github.com/googleads/google-ads-php/tree/main/src/Google/Ads/GoogleAds/V16/Services/Client

**Expected behavior:**

They should not be marked as final.

**Request/Response Logs:**

 
**Anything else we should know about your project / environment:**

As I could not reopen #347, I wrote new issue here.

**Comment by fiboknacky** [comment]
Thanks for reporting.
It looks like what you reported is different from #347, so it should be a separate issue.

That one is about making the `GoogleAdsClient` final, but from what you said, you'd like generated clients to be final.
I know that the previously generated classes didn't have the "final" modifier before, but due to [GAPIC v2 generation](https://developers.google.com/google-ads/api/docs/client-libs/php/gapic), they now have "final".

Could you tell me more what's your use case is? Are there any special functionalities that you need to inject into the classes before using them to send a request to the API server?

**Comment by 77web** [comment]
@fiboknacky Hi, thank you for your reply.
Our usecase is the same as #347, we want to unit test our class that depends of Service Client classes.
For our test should not call real API, we usually mock Service Client classes, and final classes cannot be mocked in PHP.

Our code is like this:
```php
<?php

class FooBarMyClass
{
    public function __construct(
        private readonly $someServiceClient,
    ) {
    }

    public function execute(): void
    {
        // actually some complexed logic to calculate some-proper-request-param will be here
        $this->someServiceClient->someApiCallMethod(new SomeServiceClientRequest('some-proper-request-param'));
    }
}
```

We want to write tests like this:
```php
<?php

class FooBarMyClassTest extends TestCase
{
    public function testExecute(): void
    {
        // ensure ServiceClient should be called with proper request params
        $serviceClientMock = $this->createMock(SomeServiceClient::class);
        $serviceClientMock->expects($this->once())
            ->method('someApiCallMethod')
            ->with(new SomeServiceClientRequest('some-proper-request-param'))

        ;

        $SUT = new FooBarMyClass($serviceClientMock);
        $actual = $SUT->execute();
    }
}
```

**Comment by bshaffer** [comment]
Follow the instructions here in order to mock classes marked as `final` in PHPUnit: https://tomasvotruba.com/blog/2019/03/28/how-to-mock-final-classes-in-phpunit

I was able to mock classes marked as `final` by installing `"dg/bypass-finals: ^1.6"` as a `--dev` dependency, and adding `DG\BypassFinals::enable();` to our `bootstrap.php` file for testing. I

**NOTE: ** It's necessary to add this in the bootstrap file so it loads before any of the classes marked as `final`, otherwise it won't work.
