### ISSUE TITLE
Class BatchJobServiceClient no longer exists, but according to example already

### ISSUE THREAD

**Issue by cbringmann** [googleads/google-ads-php#1010]
Client library and Google Ads API versions:
- Client library version: v22.1.0
- Google Ads API version: V16

As we are currently migrating to V16, we have noticed that the class *Google\Ads\GoogleAds\V16\Services\BatchJobServiceClient* no longer exists in V16.

Is this intentional, but according to Example, it should still be there.
https://github.com/googleads/google-ads-php/blob/main/examples/CampaignManagement/AddCompleteCampaignsUsingBatchJob.php

**Comment by fiboknacky** [comment]
Sorry for this confusion. We've upgraded all classes to [GAPIC v2](https://developers.google.com/google-ads/api/docs/client-libs/php/gapic) now, so some examples need to be updated to use "Google\Ads\GoogleAds\V16\Services\Clients" instead of "Google\Ads\GoogleAds\V16\Services".
I'll do this as soon as I can.

**Comment by fiboknacky** [comment]
This is fixed with [v23.0.0](https://github.com/googleads/google-ads-php/releases/tag/v23.0.0)
