### ISSUE TITLE
Upgrade Version V1 to V2

### ISSUE THREAD

**Issue by kuldeep1984** [googleads/google-ads-php#211]
how to upgrade https://github.com/googleads/google-ads-php API version from V1 to V2. 
I have used V1 version and now V2 is out and want to upgrade it. What are the steps? Please Help.

**Comment by fiboknacky** [comment]
First, do `git pull` to pull all the latest changes from master. (Alternatively, you could pick up specific release by go to [this section](https://github.com/googleads/google-ads-php/releases/) and download its source code as a zip file)
After that, modify your existing code to use the v2 endpoint instead of v1.

Then, make sure take a look at this [migration note](https://developers.google.com/google-ads/api/docs/migration-v1-v2) and modify any part of your code that needs changes.

Hope this help.

**Comment by kuldeep1984** [comment]
Thanks for the quick reply. I will try to follow these steps.
