### ISSUE TITLE
ERROR at select awql

### ISSUE THREAD

**Issue by fabianamanu** [googleads/google-ads-php#215]
I'm sorry for the bad English, but I have a selector on it I select clicks and others more there run I get the following error below and I'm sorry if it's some silly mistake because I'm new with this api

http://72.55.140.9/adwordsapi?query=Select AdvertisingChannelType,CampaignId,CampaignName,CampaignStatus,Date,Amount,Cost,Ctr,Clicks,Conversions,ConversionRate,ConversionValue,CostPerAllConversion,CostPerConversion,ImpressionReach,Impressions,InteractionRate,Interactions,PercentNewVisitors,ValuePerAllConversion,ValuePerConversion,VideoQuartile100Rate,VideoQuartile25Rate,VideoQuartile50Rate,VideoQuartile75Rate,VideoViewRate,VideoViews,ViewThroughConversions,AccountDescriptiveName from CAMPAIGN_PERFORMANCE_REPORT during 20190816,20190816&token=cVgOqBbHn6eJx8Mxo5gnHQ
![api](https://user-images.githubusercontent.com/12700210/66124718-871d4c00-e5bb-11e9-85be-80aea268d599.png)

**Comment by PierrickVoulet** [comment]
Hi @fabianamanu - Based on the description you make, you are using the [AdWords API](https://developers.google.com/adwords/api/docs/guides/start), not the [Google Ads API](https://developers.google.com/google-ads/api/docs/start). The client library for PHP related to AdWords API is hosted in a different [GitHub repository](https://github.com/googleads/googleads-php-lib), could you please post your issue there instead?

In the meantime I am closing this issue because out of scope of this GitHub repository.
