### ISSUE TITLE
getStatus is empty?

### ISSUE THREAD

**Issue by GlobalWarmingIsntReal** [googleads/google-ads-php#219]
Using the example GetCampaigns.php script, when trying to grab getStatus on top of the included getId, and getName, getStatus seems to return 0?

For example:
```
printf(
    "Campaign with ID %d and name '%s' was found - Status: %s.%s",
    $googleAdsRow->getCampaign()->getId()->getValue(),
    $googleAdsRow->getCampaign()->getName()->getValue(),
    $googleAdsRow->getCampaign()->getStatus(),
    PHP_EOL
);
```

**Comment by PierrickVoulet** [comment]
This is because you are getting the index of the enumerable.

If you want to get the name you need to use the method "name" provided in the associated enumerable class. Here is a good example how to do such a thing in the context of the [billing status](https://github.com/googleads/google-ads-php/blob/84860ce32f0f0947e92a2358586d0b41b05a2512/examples/Billing/GetBillingSetup.php#L135).

In your case you need to use the [CampaignStatus](https://github.com/googleads/google-ads-php/blob/master/src/Google/Ads/GoogleAds/V2/Enums/CampaignStatusEnum/CampaignStatus.php) enumerable class instead.

**Comment by fiboknacky** [comment]
Closing because an answer is provided.
