### ISSUE TITLE
Google Ads API reporting run result error

### ISSUE THREAD

**Issue by shanglei001** [googleads/google-ads-php#245]
Hi,
We are writing to you to confirm how to get the right data results by Web. We could get the right data results by Google Ads API, visiting GetCampaigns.php. Now we would like to get the right data results by Web as follows: https://github.com/googleads/google-ads-php/blob/master/examples/BasicOperations/GetCampaigns.php

Run result error:
[
![1](https://user-images.githubusercontent.com/34848634/70303133-c9703d00-1839-11ea-9a8d-67b77427eb82.png)
](url)

[0] InvalidArgumentException in /google-ads-php/vendor/ulrichsg/getopt-php/src/Option.php line 242
Option mode must be one of GetOpt::NO_ARGUMENT, GetOpt::OPTIONAL_ARGUMENT, GetOpt::REQUIRED_ARGUMENT and GetOpt::MULTIPLE_ARGUMENT

Invoking code as follows (The test error shows in the red box  ):
![2](https://user-images.githubusercontent.com/34848634/70303160-e3aa1b00-1839-11ea-84f4-d8b417287b66.png)

`$options = (new ArgumentParser())->parseCommandArguments([
   ArgumentNames::CUSTOMER_ID => self::CUSTOMER_ID
        ]);`

This code has an internal assignment error. We did a lot of research and found no one had ever had s similar problem like us.

We will be appreciated if we could get your kindly help.

Best regards,
Leo

**Comment by fiboknacky** [comment]
Hi Leo,

As stated in Step 5 of [this section](https://github.com/googleads/google-ads-php#getting-started), our code examples are not meant to be executed as a web application.
One issue that can happen is like what you're facing: We use command-line argument parser in our code, so that it's convenient to run from command prompt.
So, when you run as a web page, it doesn't supply any required arguments, and thus it fails.

If you wish to run GetCampaigns as a web page, please copy the core code (lines inside [runExample()](https://github.com/googleads/google-ads-php/blob/master/examples/BasicOperations/GetCampaigns.php#L93)) and put it in your web application, then modify the output printing part accordingly (e.g., using echo instead of printf).

Hope this help.

Best,
Knack
