### ISSUE TITLE
Some of the Functions are missing.

### ISSUE THREAD

**Issue by chiragvels** [googleads/google-ads-php#437]
Hi,

I am trying to migrate from V3, V4 to V5.

I was using function getNameUnwrapped and similar Unwrapped one.

Is that any reason why it was missing from V5?

Error I was facing 

> "Call to undefined method Google\Ads\GoogleAds\V5\Common\TargetRestriction::getBidOnlyUnwrapped()"
> 
> Call to undefined method Google\Ads\GoogleAds\V5\Resources\Campaign::getNameUnwrapped()

Can you please help when to use?

Thanks,

**Comment by fiboknacky** [comment]
Please see the [migration note](https://developers.google.com/google-ads/api/docs/version-migration#services) .
Some of the resources have been migrated to use [field presence](https://github.com/protocolbuffers/protobuf/blob/master/docs/field_presence.md) such as optional string and optional double instead of [wrapper types](https://developers.google.com/google-ads/api/docs/client-libs/python/wrapper-types) such as StringValue and DoubleValue. 

That's why the generated classes don't contain methods like `getNameUnwrapped()` anymore.
