### ISSUE TITLE
Fetch data PHP/ How to write query?

### ISSUE THREAD

**Issue by chrisooo3** [googleads/google-ads-php#451]
Hi,
I need to fetch: |Name of campaign||Impressions|Cost||Conversation Rate||Conversions||Date||Budget||Image/Video of this ad||
Can I fetch it all from campaign entity? How?
```php
        $googleAdsServiceClient = $googleAdsClient->getGoogleAdsServiceClient();
        // Creates a query that retrieves all campaigns.
        $query = 'SELECT [MYLIST]  FROM campaign ORDER BY campaign.name';
        // Issues a search stream request.
        /** @var GoogleAdsServerStreamDecorator $stream */
        $stream =
            $googleAdsServiceClient->searchStream($customerId, $query);

            // Iterates over all rows in all messages and prints the requested field values for
            // the campaign in each row.
            foreach ($stream->iterateAllElements() as $googleAdsRow) {
                /** @var GoogleAdsRow $googleAdsRow */
                printf(
                "Campaign with ID %d and name '%s' was found.%s",
                $googleAdsRow->getCampaign()->getId(),
                $googleAdsRow->getCampaign()->getName(),
                AND SOMETHING HERE
                PHP_EOL
            );
        }
```

**Comment by PierrickVoulet** [comment]
Hi @chrisooo3 - You will need to build a GAQL query for the request. You will find complete documentation on the [Google Ads API developer website](https://developers.google.com/google-ads/api), e.g., [reporting](https://developers.google.com/google-ads/api/docs/reporting/overview), [campaign resource](https://developers.google.com/google-ads/api/fields/v6/campaign), [Interactive GAQL builder](https://developers.google.com/google-ads/api/docs/query/interactive-gaql-builder).

I am closing this issue because your question relates to the API and not the library but feel free to reopen if you have follow up questions about the library.

**Comment by chrisooo3** [comment]
@PierrickVoulet could you tell how? I am searching for 4 hours and could not find it.

**Comment by PierrickVoulet** [comment]
Typically, you would create something like `SELECT campaign.name, metrics.impressions, metrics.cost_micros, metrics.conversions_from_interactions_rate, metrics.conversions_from_interactions_rate FROM ad_group_ad` to get data about ad group ads. For more details, you can check the documentation of the `ad_group_ad` report that is available [here](https://developers.google.com/google-ads/api/fields/v6/ad_group_ad).

If you have further questions on how to use the API or GAQL queries, feel free to use the [dedicated support of the Google Ads API](https://developers.google.com/google-ads/api/support).
