### ISSUE TITLE
bug with float numbers 

### ISSUE THREAD

**Issue by devorel** [googleads/google-ads-php#520]
https://github.com/googleads/google-ads-php/blob/a2432673c876025a76050149fa1933c4788045e2/examples/Utils/Helper.php#L65

i get bug when i use in the function **mutateKeywordPlanAdGroupKeywords** ,
the function can't get **full** float numbers
`        $response = $keywordPlanAdGroupKeywordServiceClient->mutateKeywordPlanAdGroupKeywords($customerId, $keywordPlanAdGroupKeywordOperations);
`

look , for number 24.238962
in the regular function i get 24238962
`$amount ? (int) ($amount * 1000000) : 0;`

but it's stop with bug .
when i use with this 

in the this function i get 24240000 , and it's works well 
`(int) str_replace('.', '', number_format($amount, 2, '.', '') . '0000');`

example code with  mutateKeywordPlanAdGroupKeywords function 
https://developers.google.cn/google-ads/api/docs/keyword-planning/generate-forecast-metrics?hl=zh-cn#php

**Comment by devorel** [comment]
Google\Ads\GoogleAds\Lib\V6\GoogleAdsException
{ "message": "Request contains an invalid argument.", "code": 3, "status": "INVALID_ARGUMENT", "details": [ { "@type": "google.ads.googleads.v6.errors.googleadsfailure-bin", "data": "<Unknown Binary Data>" }, { "@type": "grpc-status-details-bin", "data": "<Unknown Binary Data>" }, { "@type": "request-id", "data": "SxAmu0LJPFTaReqpzkUpwg" } ] }

**Comment by PierrickVoulet** [comment]
Hi @devorel - thank you for reporting the issue.

In order to replicate on our side, could you provide the following information:

**What versions of the client library and Google Ads API are you using?**

- Client library (format: `vX.Y.Z`): the exhaustive list of all released versions of the client library is in the repository [releases' page](https://github.com/googleads/google-ads-php/releases).
- Google Ads API (format: `VX`): you can find the major version of the Google Ads API used by checking the namespace of your `GoogleAdsClient`, e.g., `Google\Ads\GoogleAds\Lib\V6\GoogleAdsClient`.

**What environment are you using?**

The output generated by the script [`scripts/print_php_information.php`](https://github.com/googleads/google-ads-php/blob/master/scripts/print_php_information.php) can be used. Alternatively, you can provide with the following information:

- The PHP version: run `php -v`.
- The name and version of the operating system: run `php -r 'print php_uname();'`.
- Whether the C implementation of `protobuf` is used or not (see [details](https://developers.google.com/google-ads/api/docs/client-libs/php/protobuf)): run `php -r 'print phpversion("protobuf");'`.
- Whether the transport used is gRPC or REST (see [details](https://developers.google.com/google-ads/api/docs/client-libs/php/transport)): run `php -r 'print phpversion("grpc");'` and provide the value of the `transport` [client configuration](https://developers.google.com/google-ads/api/docs/client-libs/php/configuration) setting if set.

**Actions taken**

Please provide a code snippet or steps to consistently reproduce the experienced behavior.

**Expected result**

**Actual result**

Make sure to include information that can help us debug (full error message, exception listing, stack trace, [logs](https://developers.google.com/google-ads/api/docs/client-libs/php/logging)).
See [troubleshooting](https://developers.google.com/google-ads/api/docs/best-practices/troubleshooting) for how to diagnose problems better.
 
**Anything else we should know about your project / environment**

**Comment by devorel** [comment]
Hi , 
i use with gRPC 

PHP 7.3.22-1+0~20200909.67+debian9~1.gbpdd7b72 (cli) (built: Sep  9 2020 06:54:34) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.22, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.22-1+0~20200909.67+debian9~1.gbpdd7b72, Copyright (c) 1999-2018, by Zend Technologies

# php -r 'print php_uname();'
Linux sd-4.9.0-14-amd64 #1 SMP Debian 4.9.246-2 (2020-12-17) x86_64

# php -r 'print phpversion("protobuf");'

# php -r 'print phpversion("grpc");'
1.31.1

**Comment by PierrickVoulet** [comment]
Thanks. The issue is not coming from the Helper method implementation but from the value you provide in your request that does not follow the minimum unit rules which depends on the [currency used](https://developers.google.com/adwords/api/docs/appendix/codes-formats#expandable-18).

In other words requesting the Google Ads API with the value `24238962` does not work because is in not divisible by the minimum unit of the currency you are using but `24240000` does. This is not related to our client  library but how to use the Google Ads API itself, feel free to [contact the dedicated team](https://developers.google.com/google-ads/api/support) in case you have follow up questions on this.

**Comment by devorel** [comment]
Hi
the value 24238962 i get from google-ADS , 
it's does not matters 24238962 or 24240000 , 
what i say it the mutateKeywordPlanAdGroupKeywords function don't know how to provide with full float numbers.
the Php-Api need to fix value automictic by minimum unit rules.

**Comment by PierrickVoulet** [comment]
I am not sure to understand what you mean. Could you please provide some executable code that illustrates the issue you are describing so that we can replicate and fix?

**Comment by devorel** [comment]
if you want fix it just put this .
return $amount ? ((int) ($amount * 100)) * 10000 : 0;

it return  24240000 , and not 24238962
