### ISSUE TITLE
Metrics Iteration Help [Reporting] [Question]

### ISSUE THREAD

**Issue by Gismogy** [googleads/google-ads-php#521]
# Questions about Metrics Iteration

### Info
I have been working with the API for around a month now.
Most things worked until now, but i am heavly struggling with Metrics.

I have been on the Google API forums for a while and i got pointed here, because you guys know more about this.

## Question

Simply said, I cant seem to find the functions for the metrics reporting.

I have found them from Campaigns & Ads, but i cant seem to find it.
After, i found the file : Metrics, But the moment i call any function from that file, it doenst work.

### Query
(Note, i know Table.* doesnt work, but its for making things shorter)
Metrics.* & Campaign.* From Campaign

**Comment by fiboknacky** [comment]
Could you point us to the Google Ads API forum where you first communicated as well?
And I need more information about your question. 

> I have found them from Campaigns & Ads, but i cant seem to find it.
> After, i found the file : Metrics, But the moment i call any function from that file, it doenst work.

What do you mean by this? Could you include your code snippet? I just need to make sure I understand "metrics reporting" that you mentioned correctly. Thanks.

**Comment by Gismogy** [comment]
### the Google ads api forum : 
https://groups.google.com/forum/?hl=en#!forum/adwords-api 
### or my post : 
https://groups.google.com/g/adwords-api/c/ErsEyXyfhVo

> I have found them from Campaigns & Ads, but i cant seem to find it.
After, i found the file : Metrics, But the moment i call any function from that file, it doenst work.

i found the Files :
**Campaigns.php & ad.php in (google-ads-php\src\Google\Ads\GoogleAds\V6\Resources)\**
To retrieve Data From Campaign & And AD objects (shown in picture)

But i cant find the file, with the Functions to retrieve Data out of the CampaignMetrics (shown in the picture). 
![image](https://user-images.githubusercontent.com/31318693/105982301-640f8900-6097-11eb-8f6b-2958323d494a.png)

**Comment by fiboknacky** [comment]
Could you check [this example](https://github.com/googleads/google-ads-php/blob/master/examples/Reporting/GetKeywordStats.php)? It should show you what you should do in your case.

**Comment by Gismogy** [comment]
The Functions in this example works, but where does the function come from that is connected to : 
![image](https://user-images.githubusercontent.com/31318693/106110619-3e43bc00-614b-11eb-9b67-8ae4a4e3d01e.png)
![image](https://user-images.githubusercontent.com/31318693/106110642-46036080-614b-11eb-9d88-a617d0731375.png)

since I have been searching all over the place but i cant seem to find it.
(and the functions work)

**Comment by fiboknacky** [comment]
It's in [this line](https://github.com/googleads/google-ads-php/blob/master/examples/Reporting/GetKeywordStats.php#L136).

**Comment by Gismogy** [comment]
i meant something else.

i am getting the Metrics Data. BUT, taking Aditional Data out is the question.

because currently i am able to use : 
                $metrics->getImpressions(),
                $metrics->getClicks(),
                $metrics->getCostMicros(),

BUT are there more Metric functions i can call.
 like $metrics->getCostFunction() [Just a example]

my excuses if my english isnt the best.

**Comment by fiboknacky** [comment]
No worries for your English. I'm not a native speaker too. :)

> BUT are there more Metric functions i can call. like $metrics->getCostFunction() [Just a example]

I guess you mean you get nothing when calling other `$metrics->getXXX()` methods, right?
You need to request the fields you want to fetch in your [query string](https://github.com/googleads/google-ads-php/blob/master/examples/Reporting/GetKeywordStats.php#L114) first.

It looks like you might need more guidance regarding how the Google Ads API works.
This is [the guide](https://developers.google.com/google-ads/api/docs/reporting/example) about reporting that you can read through.
I've already informed the agent working on [your case in the forum](https://groups.google.com/g/adwords-api/c/ErsEyXyfhVo) to help you understand the Google Ads API. Just let him know your questions.

As this issue is not really about using the client library, but more about how to use the API, I'll close it for now.
Feel free to get back here if you have other library-related issues.
