### ISSUE TITLE
Unable to run Laravel Application on Linux/nginx Server 

### ISSUE THREAD

**Issue by SubaKrishnan** [googleads/google-ads-php#523]
Hi,
I had implemented the LaravelSampleApp by adding the extensions, It works well in Local system. But in Live, I have Linux/Nginx server. Here also I had done the same process by installing the extensions & enabled at php.ini file. But gRPC is not working in Nginx Server.

In live, shouts error as 
"gRPC support has been requested but required dependencies have not been found. For details on how to install the gRPC extension please see https://cloud.google.com/php/grpc. "

But, I have gRPC & protobuf at my server 

Also, I had edit the Nginx config file by adding the line "grpc_pass grpc://localhost:50051"

I made a try by referring this document [Nginx Setup](https://www.nginx.com/blog/nginx-1-13-10-grpc/)  But nothing helps. 
Can you guide me on how to do the setup at Linux/Nginx System? 

I would like to know how to configure grpc at Nginx server 

If gRPC is not possible. I would like to know how to implement the LaravelSampleApp using the REST Transport

When I set the transport as rest in google_ads_php.ini. It shows 
"Streaming calls are not supported while using the REST transport"

![image](https://user-images.githubusercontent.com/54890552/106276554-c2866400-625d-11eb-89a8-4b49d3189faf.png)

**Comment by PierrickVoulet** [comment]
Hi @SubaKrishnan,

When the gRPC PHP extension is not available on the system, PHP falls back and uses the gRPC package and REST transport (see full detail [here](https://developers.google.com/google-ads/api/docs/client-libs/php/transport)). The issue is that the REST transport does _not_ support streaming (because it is not HTTP/2 compliant) but the LaravelSampleApp code example _does_ use it by calling the GoogleAdsService.SearchStream method to execute search queries.

One alternative is to change from GoogleAdsService.SearchStream to GoogleAdsService.Search so that your application does not rely on streaming at all but this may lead to other issues, typically higher latency (see full detail [here](https://developers.google.com/google-ads/api/docs/reporting/streaming?hl=en)).

The best would be to fix your Nginx setup so that the gRPC PHP extension is available to the application. I suggest you to contact the Nginx community as they should be much better suited to help you with this. Here are links I could find: [community home](https://www.nginx.com/resources/wiki/community), [get involved](https://www.nginx.com/resources/wiki/community/get_involved).

**Comment by SubaKrishnan** [comment]
Thanks for you help.

I had followed the instructions you gave me. It works well
