### ISSUE TITLE
How to mock GoogleAdsFailure?

### ISSUE THREAD

**Issue by lezhnev74** [googleads/google-ads-php#539]
Following on #294, sometimes I need to imitate API error response, so I want to throw `GoogleAdsFailure` with my custom error that I provide manually. Interesting, that I can't mock it because the whole php fails with `Segmentation fault` (`protobuf` and `grpc` extensions enabled). 

This is an example of code which fails:
```php
$serializedErrorsAsJson = 'my serialized error representation';
$googleAdsFailure = \Mockery::mock(GoogleAdsFailure::class);
$googleAdsFailure->shouldReceive('serializeToJsonString')->andReturn($serializedErrorsAsJson);        
```

I tried to do it this way:
```php
$googleAdsFailure = new GoogleAdsFailure([
            'errors' => [
                new GoogleAdsError([
                    'error_code' => new ErrorCode([
                        'customer_manager_link_error' => ManagerLinkError::INVALID_CHANGE,
                    ]),
                    'message' => 'The change for mutate link is invalid.',
                ])
            ]
        ]);
```

That seems to work. However here I can only provide an error code as an integer, while actual error that happens in real responses contains a string. I feel that somewhere inside of your package the integer is converted to appropriate message.

So if I use the above example, when I serialize `$googleAdsFailure->serializeToJsonString()` I get:
```json
{"errors":[{"errorCode":{"customerManagerLinkError":18},"message":"The change for mutate link is invalid."}]}
``` 

While in production when I serialize I see this type of output:
```json
{"errors":[
    {
      "errorCode":{"managerLinkError":"INVALID_CHANGE"},  <------- see
      "message":"The change for mutate link is invalid.",
      ...
   }
]}
```

How would you mock errors? Any hints are appreciated!
My final goal is to be able to control what `serializeToJsonString()` returns. I tried my options:
- mocking the whole object
- creating a real object with manual errors.

**Comment by fiboknacky** [comment]
Hello Dmitry,

> php fails with Segmentation fault (protobuf and grpc extensions enabled).

Sorry for your inconvenience. protobuf sometimes doesn't work well with the serialization function.
Could you show your code, tell what protobuf version you use and whether it's [the C implementation or PHP implementation](https://developers.google.com/google-ads/api/docs/client-libs/php/protobuf)?

For creating the `GoogleAdsFailure` object, we use [this method](https://github.com/googleads/google-ads-php/blob/8df5189e92125e041f355ea79f564eac84fcaaa1/src/Google/Ads/GoogleAds/Lib/V6/StatusMetadataExtractor.php#L38) to extract it from the metadata, using [`mergeFromString()`](https://github.com/googleads/google-ads-php/blob/8df5189e92125e041f355ea79f564eac84fcaaa1/src/Google/Ads/GoogleAds/Lib/V6/StatusMetadataExtractor.php#L50).

I don't expect that to be the source of the difference, when its `serializeToJsonString()` is called, but could you try and see if you can get the expected result?

Best,
Knack

**Comment by lezhnev74** [comment]
Yup.

> Could you show your code, 

```php
<?php

namespace Test;

use Google\Ads\GoogleAds\V4\Errors\ErrorCode;
use Google\Ads\GoogleAds\V4\Errors\GoogleAdsError;
use Google\Ads\GoogleAds\V4\Errors\GoogleAdsFailure;
use Google\Ads\GoogleAds\V4\Errors\ManagerLinkErrorEnum\ManagerLinkError;

require "vendor/autoload.php";

$googleAdsFailure = new GoogleAdsFailure([
    'errors' => [
        new GoogleAdsError([
            'error_code' => new ErrorCode([
                'customer_manager_link_error' => ManagerLinkError::INVALID_CHANGE,
            ]),
            'message' => 'The change for mutate link is invalid.',
        ])
    ]
]);

echo $googleAdsFailure->serializeToJsonString();
```

> tell what protobuf version you use and whether it's the C implementation or PHP implementation?
```
> php -m | grep protobuf
protobuf 

> php -i | grep protobuf
protobuf
protobuf.keep_descriptor_pool_after_request => 0 => 0

> composer info | grep protobuf
google/protobuf                          v3.14.0            proto library for PHP
```
It is supposed to be using C-extension if it is installed, isn't it?


> For creating the GoogleAdsFailure object, we use this method to extract it from the metadata, using mergeFromString().
Hm, yeah, here my knowledge of protobuf is a bit limited. I am not sure how to make up a string representation of an error so it can parse it. Can you provide a sample how this is done for testing purposes? Thank you!

**Comment by fiboknacky** [comment]
I found the root cause. In short, the reason why you get a number instead of the enum string is because you're using a wrong enum value at first.

You should pass an enum value of [CustomerManagerLinkError](https://github.com/googleads/google-ads-php/blob/8df5189e92125e041f355ea79f564eac84fcaaa1/src/Google/Ads/GoogleAds/V6/Errors/CustomerManagerLinkErrorEnum/CustomerManagerLinkError.php) to `customer_manager_link_error`, not the one of `ManagerLinkError`, i.e., do like this instead:

```php
$googleAdsFailure = new GoogleAdsFailure([
    'errors' => [
        new GoogleAdsError([
            'error_code' => new ErrorCode([
                'customer_manager_link_error' => CustomerManagerLinkError::DUPLICATE_CHILD_FOUND,
            ]),
            'message' => 'The change for mutate link is invalid.',
        ])
    ]
]);
```

Protobuf allows you to set any value to a field, because in PHP, there is no simple way to detect if you pass a valid value belonging to the enum we want.
As a rule of thumb for this client library, whenever you set an enum value to a field, you'd need to use values of the enum whose name is _the same as that of the field_, e.g., using a value of `CustomerManagerLinkError` for setting the `customer_manager_link_error` field.

If you pass other values, it'll allow you to do so, but it will still fail at the API server side. (For this particular case, it's not realistic to do so, as you'd not pass this `GoogleAdsFailure` object to the server though).
The side effect for doing that is the `serializeToJsonString` method will not work properly, as it cannot find a correct mapped string for your value. 

For this case, the value you pass is 18, but the [corresponding enum class](https://github.com/googleads/google-ads-php/blob/8df5189e92125e041f355ea79f564eac84fcaaa1/src/Google/Ads/GoogleAds/V6/Errors/CustomerManagerLinkErrorEnum/CustomerManagerLinkError.php#L14) has a value up to 10.
That's why `serializeToJsonString` treats 18 as is, and doesn't convert it to a string.

Using the above example of mine, you would get something like this:

```
{"errors":[{"errorCode":{"customerManagerLinkError":"DUPLICATE_CHILD_FOUND"},"message":"The change for mutate link is invalid."}]}
```

**Comment by lezhnev74** [comment]
Aha, thank you @fiboknacky ! 👍 
p.s. I hope you'll have time at some point to publish a proper guide for testing Google API calls.

**Comment by fiboknacky** [comment]
Thanks for the feedback. We'll take that into consideration. :)
