### ISSUE TITLE
Change Status Enum values not matched with ID provided

### ISSUE THREAD

**Issue by chiragvels** [googleads/google-ads-php#581]
Hi,

I may be looking at wrong file but please let me know how we can retrive valued from ID.

Here in [API docs](https://developers.google.com/google-ads/api/docs/change-status#change_status_types) the Ids provide is wrong mapped in enum file [here](src/Google/Ads/GoogleAds/V6/Enums/ChangeStatusResourceTypeEnum/ChangeStatusResourceType.php).

For e.g AD_GROUP_AD has Resource type ID is 3
But in ENUM file it is const AD_GROUP_AD = 4;

Please correct me If I need to look at other file for ID.

Thanks,

**Comment by mcloonan** [comment]
The IDs in the doc you linked are not meant to map to the public protos. They instead represent what the resource type ID will come back as in the *resource name* of the entity. They should only be used in the rare case that a response contains an UNKNOWN resource type; they should not be your primary way to identify the type of the row.

We're looking at improving that doc page to make this clearer.

**Comment by PierrickVoulet** [comment]
Thank you @chiragvels for raising the concern and @mcloonan for answering. We just improved the API docs to avoid the confusion. I am closing this issue because nothing is wrong in this library, feel free to contact the [Google Ads API support](https://developers.google.com/google-ads/api/support) if you have any follow up questions about this.
