### ISSUE TITLE
Paging Fail

### ISSUE THREAD

**Issue by jrodrigueznorte** [googleads/google-ads-php#61]
well i have this error ( ERR_EMPTY_RESPONSE ): 

![image](https://user-images.githubusercontent.com/49953224/56672966-5be61680-6685-11e9-99a3-65a996d439b6.png)

when try paginate the results.
this is my entire code:

`
class Util
{

    public static function getIdUnformat($id)
    {
        $id_adwords=str_replace('-', '', $id);
        return $id_adwords;
    }

    public static function getGoogleAdsClient()
    {
        $cliente_id       = env('ADWORDS_CLIENT_ID');
        $cliente_secret   = env('ADWORDS_CLIENT_SECRET');
        $token            = env('ADWORDS_TOKEN');
        $developer_token  = env('ADWORDS_DEVELOPER_TOKEN');
        $id_account_mcc   = self::getIdUnformat(env('ADWORDS_ID_MCC'));

        $oAuth2Credential = (new OAuth2TokenBuilder())
      ->withClientId($cliente_id)
      ->withClientSecret($cliente_secret)
      ->withRefreshToken($token)
      ->build();

        $googleAdsClient = (new GoogleAdsClientBuilder())
        ->withDeveloperToken($developer_token)
        ->withLoginCustomerId($id_account_mcc)
        ->withOAuth2Credential($oAuth2Credential)
        ->build();
        return $googleAdsClient;
    }
}

class TestController extends Controller
{
    const PAGE_SIZE = 100;

    public function convertionAction()
    {
        $cid = "xxx-xxx-xxxx";

        $cid = Util::getIdUnformat($cid);
        $googleAdsClient = Util::getGoogleAdsClient();
        $googleAdsServiceClient = $googleAdsClient->getGoogleAdsServiceClient();

        $query = "SELECT
                 ad_group.id, ad_group.status
            FROM
                ad_group
            WHERE
                ad_group.status = 'ENABLED' ";

        $response = $googleAdsServiceClient->search($cid, $query, ['pageSize' => self::PAGE_SIZE]);

        foreach ($response->iterateAllElements() as $googleAdsRow) {
            printf(
                "ad_group.name %s, ad_group.status %s%s",
                $googleAdsRow->getAdGroup()->getId()->getValue(),
                $googleAdsRow->getAdGroup()->getStatus(),
                PHP_EOL
            );
        }

    }
}
`

then if i use ['pageSize' => self::PAGE_SIZE] with $response->iterateAllElements() always get this error in the browser. i  always get the same error.

but if i remove the paginate ['pageSize' => self::PAGE_SIZE]  i can paginate all results. this is the code:

`
class Util
{

    public static function getIdUnformat($id)
    {
        $id_adwords=str_replace('-', '', $id);
        return $id_adwords;
    }

    public static function getGoogleAdsClient()
    {
        $cliente_id       = env('ADWORDS_CLIENT_ID');
        $cliente_secret   = env('ADWORDS_CLIENT_SECRET');
        $token            = env('ADWORDS_TOKEN');
        $developer_token  = env('ADWORDS_DEVELOPER_TOKEN');
        $id_account_mcc   = self::getIdUnformat(env('ADWORDS_ID_MCC'));

        $oAuth2Credential = (new OAuth2TokenBuilder())
      ->withClientId($cliente_id)
      ->withClientSecret($cliente_secret)
      ->withRefreshToken($token)
      ->build();

        $googleAdsClient = (new GoogleAdsClientBuilder())
        ->withDeveloperToken($developer_token)
        ->withLoginCustomerId($id_account_mcc)
        ->withOAuth2Credential($oAuth2Credential)
        ->build();
        return $googleAdsClient;
    }
}

class TestController extends Controller
{
    const PAGE_SIZE = 100;

    public function convertionAction()
    {
        $cid = "xxx-xxx-xxxx";

        $cid = Util::getIdUnformat($cid);
        $googleAdsClient = Util::getGoogleAdsClient();
        $googleAdsServiceClient = $googleAdsClient->getGoogleAdsServiceClient();

        $query = "SELECT
                 ad_group.id, ad_group.status
            FROM
                ad_group
            WHERE
                ad_group.status = 'ENABLED' ";

        $response = $googleAdsServiceClient->search($cid, $query);

        foreach ($response->iterateAllElements() as $googleAdsRow) {
            printf(
                "ad_group.name %s, ad_group.status %s%s",
                $googleAdsRow->getAdGroup()->getId()->getValue(),
                $googleAdsRow->getAdGroup()->getStatus(),
                PHP_EOL
            );
        }

    }
}
`
however this not is the better way because always get one page.
somebody know what cause this?

**Comment by Raibaz** [comment]
Can you please check your server logs to see if there are any errors being logged? I'm guessing there may be some exceptions being thrown that is preventing your controller to complete its execution.

**Comment by jrodrigueznorte** [comment]
I Clean the logs before running, after running again I no have errors in the log

**Comment by jrodrigueznorte** [comment]
Hello, do you have any solution to this problem?

**Comment by Raibaz** [comment]
Hey, sorry about the late reply.

I have a couple of questions here:

- When you say that without setting the page size you always get one page, does that mean that you are still getting all the results you are expecting but they are not paginated?
- What web framework are you using? 

Since the pagination is handled asynchronously, what I think is happening here is that when the client library starts the asynchronous request for the first page the controller considers it done and starts sending the response back to the browser, but no data has actually been retrieved from the API yet.

What is your expectation here? Do you want to show only a page of results in your web page or do you want to get all of them?

In case you want to display paged results, you can do something like this:

    $page = $response->getPage() //Will return the current page
    foreach($page->getIterator() as $googleAdsRow) {
        //Print your page results
    }
    $nextPageToken = $page->getNextPageToken()

Then you can save the next page token and use that in the subsequent call to `search` like this:

    $response = $googleAdsServiceClient->search(
        $cid,
        $query,
        [
            'pageSize' => self::PAGE_SIZE,
            'pageToken' => $nextPageToken
    ]);

This will basically allow you to paginate your search results explicitly.

Does this make sense to you?

**Comment by jrodrigueznorte** [comment]
Thank you very much, in this way to iterate the results do not fail in the pagination.

**Comment by chiragvels** [comment]
Hi,

While doing pagination on /BasicOperations/GetKeywords.php
I am getting Segmentation fault: 11

And with pagination removed I can get all the results which set under the LIMIT.

Thanks,

**Comment by chiragvels** [comment]
Hello @Raibaz ,

Any input here will help me decide how to do pagination.

Thanks,

**Comment by Raibaz** [comment]
Hi, sorry for the late reply, I hadn't noticed your comments since this issue is now closed; please open a new issue the next time as comments on closed issues may go unnoticed.

There is a way to get the total_results_count field from the API response, although I understand it's not very intuitive:

`$response->getPage()->getResponseObject()->getTotalResultsCount()`

The response object you get from the `search` function is actually returning an object that wraps the response proto, so to get it you have to get it from the current page.

Also note that the page size parameter does not influence the totalResultsCount; totalResultsCount contains the number of results in all pages, not the number of results in the current page.
