### ISSUE TITLE
All versions of code under the client are available?

### ISSUE THREAD

**Issue by DongshaoZ** [googleads/google-ads-php#632]
Hi:
    The v6 client library contains code for v3, v4, v5, and v6 versions. Does this mean that all versions of code under the v6 client are available?

However, I see in https://developers.google.com/google-ads/api/docs/sunset-dates that the pre-v6 version has been deprecated, but it still works fine when I use the v4 version of the code from the v6 client library

So I want to consult, this sunset date refers to the client's sunset date or the version code's sunset date, if it refers to the client's sunset date, does it mean that after I upgrade to v8, I use the v8 client's v6 version code, my program can still work normally?

**Comment by fiboknacky** [comment]
Hello,

> The v6 client library contains code for v3, v4, v5, and v6 versions. Does this mean that all versions of code under the v6 client are available?

The short answer is no.

> However, I see in https://developers.google.com/google-ads/api/docs/sunset-dates that the pre-v6 version has been deprecated, but it still works fine when I use the v4 version of the code from the v6 client library

As you guess it right, the supported API versions would be those listed in that guide.
I believe if you send a request to v4 now, it should be an error. If not, it will definitely throw an error very soon.
The reason why you could successfully send requests to v4 would be because some clean-up processes were not 100% complete yet.

> So I want to consult, this sunset date refers to the client's sunset date or the version code's sunset date, if it refers to the client's sunset date, does it mean that after I upgrade to v8, I use the v8 client's v6 version code, my program can still work normally?

The sunset dates in the Google Ads API guide are always for the **API** versions, not the client library versions.
Note that we have other 5 libraries and their versioning could be different.

Please let me know if you have additional questions.
