### ISSUE TITLE
[AuthorizationError.USER_PERMISSION_DENIED @ ; trigger:'']

### ISSUE THREAD

**Issue by muteebahmad** [googleads/google-ads-php#74]
I am Facing this Error Can Any One Help Me Why This error Occur On API response how i can Grant The Access to Send the Invitation to customer account through API?

[AuthorizationError.USER_PERMISSION_DENIED @ ; trigger:'']

$managerCustomerID = 3435423432;

$oAuth2Credential = (new OAuth2TokenBuilder())
    ->withClientId(CLIENT_ID)
    ->withClientSecret(CLIENT_SECRET)
    ->withRefreshToken($UserRefreshToken)
    ->build();

$soapSettings = (new SoapSettingsBuilder())
    ->disableSslVerify()
    ->build();

$session = (new AdWordsSessionBuilder())
    ->withDeveloperToken(DEVELOPERTOKEN)
    ->withOAuth2Credential($oAuth2Credential)
    ->withSoapSettings($soapSettings)
    ->withClientCustomerId($CustomerID)
    ->build();

$adWordsServices = new AdWordsServices();
$ManagedCustomerService = $adWordsServices->get($session, ManagedCustomerService::class);

$operations = [];

$ManagedCustomerLink = new ManagedCustomerLink();
$ManagedCustomerLink->setClientCustomerId($CustomerID);
$ManagedCustomerLink->setLinkStatus('PENDING');
$ManagedCustomerLink->setManagerCustomerId($managerCustomerID);

$operation = new LinkOperation();
$operation->setOperand($ManagedCustomerLink);
$operation->setOperator('ADD');
$operations = [$operation];

try {

    $result = $ManagedCustomerService->mutateManager($operations);

    echo "Invite sent";
    echo "<pre>";
    print_r($result);
} catch (Exception $e) {
    echo $e->getMessage();
}

**Comment by fiboknacky** [comment]
AuthorizationError.USER_PERMISSION_DENIED can occur in this case probably because your refresh token doesn't have access to that manager account.
I'd recommend regenerating your refresh token and try again.
[This section](https://developers.google.com/adwords/api/docs/guides/accounts-overview#oauth2_credentials) of the AdWords API still applies here and would be helpful to you.

As this is related to the API in general, if you have follow-up questions, please feel free to post in [the forum](https://groups.google.com/forum/?nomobile=true#!forum/adwords-api) instead.

Best,
Knack
