### ISSUE TITLE
Protobuf deprecation notice

### ISSUE THREAD

**Issue by ujwaldhakal** [googleads/google-ads-php#744]
[DO NOT INCLUDE ANY PERSONAL OR SENSITIVE DATA - MAKE SURE TO REDACT CONTENT WHEN NECESSARY]

**Your question:**

Currently I am using "googleads/google-ads-php": "^v13.0.0" with php8.1 and I am starting to get deprecation notices like 

`Deprecated: Return type of Google\Protobuf\Internal\RepeatedField::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/google/protobuf/src/Google/Protobuf/Internal/RepeatedField.php on line 233
`

When I visit this link https://github.com/protocolbuffers/protobuf/issues/9293 it says the patch has been fixed.

**Comment by PierrickVoulet** [comment]
Hi @ujwaldhakal,

This issue was fixed by Protobuf's team but it is not released yet. We currently support [the versions `^3.19.4` of this dependency](https://github.com/googleads/google-ads-php/blob/main/composer.json#L9) so you will have the possibility to update  yours if their next version is a minor version. If their next version is a major version though, you are right, we will have to make plans to edit our rules.

**Comment by ujwaldhakal** [comment]
Thanks
