### ISSUE TITLE
can't find ArgumentParser and ArgumentName

### ISSUE THREAD

**Issue by luckiluf** [googleads/google-ads-php#782]
Hi,
I have this issue :  Uncaught Error: Class 'Google\Ads\GoogleAds\Examples\Utils\ArgumentParser' not found in /var/www/html/src/gads/GetCampaigns.php:44
and same for ArgumentName...

i want to use google ads api in my api so i download it with packagist using composer.

composer do not install the example file so i rewrite GetCampaign, ArgumentName and ArgumentParser in my API files and i didn't find how to solve this error.
Name and Parser have the namespace Google\Ads\GoogleAds\Examples\Utils (same code as on github).

**Comment by PierrickVoulet** [comment]
Hi @luckiluf - The code examples and their dependencies are only provided in dev, it is intentional. This issue is related to the setup of your application, this is difficult to troubleshoot without direct access. One thing you could try though is to relocate these files from `Google\Ads\GoogleAds` to something that you own and can easily use in your application.

**Comment by PierrickVoulet** [comment]
Closing this issue because the discussion continues in #783.
