### ISSUE TITLE
Method GeoTargetConstantServiceClient::parseName() disappeared

### ISSUE THREAD

**Issue by dmitr1y** [googleads/google-ads-php#812]
**Your client library and Google Ads API versions:**

* Client library version: `v15.0.0`
* Google Ads API version: `V10.1.0`

**Your environment:**

Not applicable.

**Description of the bug:**

In client library v14 [there was](https://github.com/googleads/google-ads-php/blob/2a7e23d246c18b36918de34fb7a73bbf4a571e2c/src/Google/Ads/GoogleAds/V9/Services/Gapic/GeoTargetConstantServiceGapicClient.php#L173-L193) the method `GeoTargetConstantServiceClient::parseName()`. But in v15 it has [disappeared](https://github.com/googleads/google-ads-php/blob/1378e99f0981b418ec232b01eb55b4529b0a5752/src/Google/Ads/GoogleAds/V10/Services/GeoTargetConstantServiceClient.php).

[Release notes for v15](https://github.com/googleads/google-ads-php/releases/tag/v15.0.0) as well as [release notes for Google Ads API v10](https://developers.google.com/google-ads/api/docs/diff-tool/v10/versus-v9/diff) do not contain any information regarding its disappearance.

Other services still retain this method. For example, [AccountLinkServiceGapicClient](https://github.com/googleads/google-ads-php/blob/main/src/Google/Ads/GoogleAds/V10/Services/Gapic/AccountLinkServiceGapicClient.php#L177-L197), [GoogleAdsFieldServiceClient](https://github.com/googleads/google-ads-php/blob/main/src/Google/Ads/GoogleAds/V10/Services/Gapic/GoogleAdsFieldServiceGapicClient.php#L171-L191), etc.

Perhaps this is a bug? Will this method be returned in the next release?

**Expected behavior:**

Method `GeoTargetConstantServiceClient::parseName()` should exists.

**Request/Response Logs:**

Not applicable.

**Anything else we should know about your project / environment:**

Not applicable.

**Comment by PierrickVoulet** [comment]
Hi @dmitr1y,

This work as intended. Between the version 9 and 10 of the Google Ads API, `the get method and any services that exclusively had a get method have been removed` (see [release notes](https://developers.google.com/google-ads/api/docs/release-notes#all_services)). This method was removed from the service because `GeoTargetConstantService` only used the resource name in the `get method` and there is a [limitation](https://github.com/googleapis/gapic-generator-php/issues/453) in the client library generator we use.

To avoid these issues, you can rely on the `ResourceName` utility in our library which is complete (see [`forGeoTargetConstant`](https://github.com/googleads/google-ads-php/blob/main/src/Google/Ads/GoogleAds/Util/V10/ResourceNames.php#L2236) in your particular case).

Thanks,
