### ISSUE TITLE
Getting error while fetching FirstPageCPC 

### ISSUE THREAD

**Issue by shobha-procentris** [googleads/google-ads-php#833]
Hello,

When we fetch the FirstPageCpc field (ad_group_criterion.position_estimates.first_page_cpc_micros) for Keyword performance report, 
we are getting the following error, can you please let us know how do we fetch the value as it is important

"None"
Fatal error:  Uncaught Error: Call to a member function getFirstPageCpcMicros() on null in /var/www/sites/psmedia/perfectstormmedia/tools/class/AdWordsAPI.class.php:5626
Stack trace:
#0 /var/www/sites/psmedia/perfectstormmedia/tools/bids/class/GoogleBidsTool.class.php(331): AdWordsAPI->getReport(Array)
#1 /var/www/sites/psmedia/perfectstormmedia/tools/bids/class/GoogleBidsTool.class.php(253): GoogleBidsTool->getSearchCampaignsReport()
#2 /var/www/sites/psmedia/perfectstormmedia/tools/bids/bidsCron.php(241): GoogleBidsTool->Keyword_Report(1)
#3 {main}
  thrown in /var/www/sites/psmedia/perfectstormmedia/tools/class/AdWordsAPI.class.php on line 5626

We are using version v10 of Google Ads API. And the version of PHP is PHP Version 7.4.29

It seems to be an issue at the PHP library as we have asked Google Ads API. Any help is highly appreciated as we have been stuck on this for quite some time

Thanks,
Shobha

**Comment by PierrickVoulet** [comment]
Hi @shobha-procentris - It seems like you are calling `getFirstPageCpcMicros` on a `null` object. It is likely that the Google Ads API returns position estimates as `null`. It does not seem to be a bug with this library but here are actions you may want to take to fix this:

1. Change your code so that it does not call `getFirstPageCpcMicros` when `ad_group_criterion.position_estimates` are `null`.
2. Enable finer [logging](https://developers.google.com/google-ads/api/docs/client-libs/php/logging) to get information about the Google Ads API requests being made and confirm with the [Google Ads API support team](https://developers.google.com/google-ads/api/support) whether `null` results are expected for these requests.
