### ISSUE TITLE
How Can i Get geo Target Constants Name Based On Resource name ?

### ISSUE THREAD

**Issue by mohammadsiabbouforwork** [googleads/google-ads-php#857]
[DO NOT INCLUDE ANY PERSONAL OR SENSITIVE DATA - MAKE SURE TO REDACT CONTENT WHEN NECESSARY]

**Your question:**

i have The Resource Name Like This : geoTargetConstants/{id} ; how can i get the name and the other data about it please ?

**Comment by fiboknacky** [comment]
You need to use the [geo_target_constant](https://developers.google.com/google-ads/api/fields/v12/geo_target_constant) report. 

Since this is related to the Google Ads API itself, if you have further questions about how to use report, could you please ask in the [dedicated forum](https://groups.google.com/g/adwords-api) for the API? Thank you.
