### ISSUE TITLE
Examples missing for Call Only and Responsive Display Ads - request

### ISSUE THREAD

**Issue by cognitive-rift** [googleads/google-ads-php#99]
Any chance of having examples for the Call Only and Responsive Display Ads? I have yet to find a good resource documenting the ad Classes in this new api version so have been making do with monkey-see, monkey do.

**Comment by fiboknacky** [comment]
Thanks for the feedback. We'll take that into consideration.

**Comment by fiboknacky** [comment]
For responsive display ads, please see [this guide](https://developers.google.com/google-ads/api/docs/responsive-display-ads/create-responsive-display-ads).
We're not going to add a specific example for that, because the majority of the code would be similar to that of [AddSmartDisplayAd](https://github.com/googleads/google-ads-php/blob/master/examples/AdvancedOperations/AddSmartDisplayAd.php).

For call-only ads, it's under consideration.

**Comment by PierrickVoulet** [comment]
Code examples that illustrate how to add Call Ads are now available: [AddCallAd](https://github.com/googleads/google-ads-php/blob/main/examples/AdvancedOperations/AddCallAd.php), [AddCall](https://github.com/googleads/google-ads-php/blob/main/examples/Extensions/AddCall.php).
